//---------------------------------------------------------------------------

#include <vcl.h>
#pragma hdrstop

#include "bal_par.h"
//---------------------------------------------------------------------------
#pragma package(smart_init)
#pragma resource "*.dfm"
TBalParForm *BalParForm;
//---------------------------------------------------------------------------
__fastcall TBalParForm::TBalParForm(TComponent* Owner)
        : TForm(Owner)
{
}
//---------------------------------------------------------------------------

