//---------------------------------------------------------------------------

#include <vcl.h>
#pragma hdrstop

#include "copy_arc.h"
//---------------------------------------------------------------------------
#pragma package(smart_init)
#pragma resource "*.dfm"
TCopyArcForm *CopyArcForm;
//---------------------------------------------------------------------------
__fastcall TCopyArcForm::TCopyArcForm(TComponent* Owner)
        : TForm(Owner)
{
}
//---------------------------------------------------------------------------

